### ISSUE TITLE
Can't open the app 

### ISSUE THREAD

**Issue by Frumkin13** [Fertion/QuickMDCapture#7]
Hello, wanted to try your app, downloaded from F-Droid,but when i open it its constantly closing itself.After some tries i get this error info,which i hope will help with issue:
java.lang.NoSuchMethodError: No static method of(J)Landroid/content/pm/PackageManager$PackageInfoFlags; in class Landroid/content/pm/PackageManager$PackageInfoFlags; or its super classes (declaration of 'android.content.pm.PackageManager$PackageInfoFlags' appears in /system/framework/framework.jar)
	at Z0.f.b(SourceFile:1)
	at com.example.quickmdcapture.MainActivityKt$MainScreen$checkLatestRelease$1.invokeSuspend(SourceFile:21)
	at e2.a.resumeWith(SourceFile:9)
	at u2.F.run(SourceFile:110)
	at androidx.compose.ui.platform.K.z(SourceFile:7)
	at androidx.compose.ui.platform.J.run(SourceFile:3)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at android.app.ActivityThread.main(Unknown Source:155)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

**Comment by Frumkin13** [comment]
> Thank you for the information. There is a slightly outdated version for now, but does the error still persist in the newer version from GitHub?

Hello again,i tried to install GitHub version on f-droid's(rooted device) but got the same thing.Then uninstalled F-droid and installed only GitHub version and everything stayed the same.I installed version 1.2.0(6),if i remember correctly in f-droid same version,hope it will help

**Comment by Frumkin13** [comment]
And my current system is:Miui 13 and android 12

**Comment by theAkito** [comment]
Same here.

```
FATAL EXCEPTION: main
Process: com.example.quickmdcapture, PID: 10936
java.lang.NoSuchMethodError: No static method of(J)Landroid/content/pm/PackageManager$PackageInfoFlags; in class Landroid/content/pm/PackageManager$PackageInfoFlags; or its super classes (declaration of 'android.content.pm.PackageManager$PackageInfoFlags' appears in /system/framework/framework.jar)
	at Z0.f.b(SourceFile:1)
	at com.example.quickmdcapture.MainActivityKt$MainScreen$checkLatestRelease$1.invokeSuspend(SourceFile:21)
	at e2.a.resumeWith(SourceFile:9)
	at u2.F.run(SourceFile:110)
	at androidx.compose.ui.platform.K.z(SourceFile:7)
	at androidx.compose.ui.platform.J.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	Suppressed: u2.D: [androidx.compose.ui.platform.k0@d2279d5, F.f@88af5ea, n0{Cancelling}@71430db, K@eddb778] 
```

Why `ZygoteInit`?

**Comment by Fertion** [comment]
@Frumkin13  @theAkito Hello. I've fixed the issue, so there shouldn't be any errors now. I would appreciate it if you could test this APK on your devices and let me know if it works for you.
[QuickMDCapture 1.2.0-release.zip](https://github.com/user-attachments/files/17498065/QuickMDCapture.1.2.0-release.zip)

**Comment by Frumkin13** [comment]
> @Frumkin13  @theAkito Hello. I've fixed the issue, so there shouldn't be any errors now. I would appreciate it if you could test this APK on your devices and let me know if it works for you.
> [QuickMDCapture 1.2.0-release.zip](https://github.com/user-attachments/files/17498065/QuickMDCapture.1.2.0-release.zip)
> Thanks for this,now it's opens correctly!Thank you for your work and quick response!Hope you'll keep up the good work!Best of luck and have a nice day!
